# Generated by Django 3.2.8 on 2021-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=6732.41, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(default='Mr', max_length=5),
            preserve_default=False,
        ),
    ]
