# Generated by Django 3.2.8 on 2021-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211109_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
